version: '2'
services: 
  app:
    build: 
      context: ./app
      dockerfile: /Users/bhagyalakshmi/Documents/mongodbLearning/app/Dockerfile
    ports:
      - '3000:3000'
    depends_on: 
      - server
  server:
    build: 
      context: ./server
      dockerfile: /Users/bhagyalakshmi/Documents/mongodbLearning/server/Dockerfile
    ports: 
      - '5000:5000'
    depends_on: 
      - mongo
  mongo:
    image: mongo
    ports: 
      - '27017:27017'
